# Generated by Django 3.1.7 on 2021-08-03 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skepsi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isDomainExpert',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isScientist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isUser',
        ),
        migrations.AddField(
            model_name='annotation',
            name='ai_data',
            field=models.TextField(blank=True, default='', max_length=50000),
        ),
        migrations.AddField(
            model_name='profile',
            name='domains',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='scoreNumber',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
