# Generated by Django 3.1.7 on 2021-07-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scoreNumber',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
