# Generated by Django 3.1.7 on 2021-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0002_auto_20210729_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ai_data',
            field=models.TextField(blank=True, default='', max_length=50000, null=True),
        ),
    ]
