# Generated by Django 3.1.7 on 2021-06-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0002_auto_20210615_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='userIsScientist',
            field=models.BooleanField(default=False),
        ),
    ]
