# Generated by Django 3.1.7 on 2021-08-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0003_auto_20210803_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domains',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
