# Generated by Django 3.1.7 on 2021-08-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0004_auto_20210803_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
