# Generated by Django 3.1.7 on 2021-08-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0005_paper_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
