# Generated by Django 3.1.7 on 2021-06-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0006_remove_annotation_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='domain',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='topic',
            name='header',
            field=models.CharField(max_length=40),
        ),
    ]
