# Generated by Django 3.1.7 on 2021-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0006_paper_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='explanation',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
