# Generated by Django 3.1.7 on 2021-08-18 18:41

from django.db import migrations, models
import django.db.models.deletion
import skepsi_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0007_auto_20210810_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=skepsi_app.models.get_upload_path)),
                ('name', models.CharField(default='', max_length=2500)),
                ('figure_number', models.IntegerField(default=1)),
                ('caption', models.TextField(default='', max_length=50000)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='skepsi_app.paper')),
            ],
        ),
    ]
