# Generated by Django 3.1.7 on 2021-06-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0007_auto_20210622_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='skepsi_app.topic'),
        ),
    ]
