# Generated by Django 3.1.7 on 2021-08-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0008_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='figure_number',
            new_name='table_number',
        ),
    ]
