# Generated by Django 3.1.7 on 2021-06-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0008_paper_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
