# Generated by Django 3.1.7 on 2021-06-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0009_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isDomainExpert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
