# Generated by Django 3.1.7 on 2021-08-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0009_auto_20210818_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='caption',
            field=models.TextField(blank=True, default='', max_length=50000),
        ),
    ]
