# Generated by Django 3.1.7 on 2021-06-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0010_auto_20210623_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='user',
            new_name='author',
        ),
    ]
