# Generated by Django 3.1.7 on 2021-06-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0011_auto_20210625_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='skepsi_app.paper'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skepsi_app.annotation'),
        ),
    ]
