# Generated by Django 3.1.7 on 2021-06-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0012_auto_20210628_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skepsi_app.annotation'),
        ),
    ]
