# Generated by Django 3.1.7 on 2021-06-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0014_annotation_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='start',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='stop',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
