# Generated by Django 3.1.7 on 2021-07-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0015_auto_20210630_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='md',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
