# Generated by Django 3.1.7 on 2021-07-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0016_paper_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='citation',
        ),
        migrations.AddField(
            model_name='paper',
            name='citationAPA',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='paper',
            name='citationChicago',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='paper',
            name='citationMLA',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='md',
            field=models.TextField(default='', max_length=50000),
        ),
    ]
