# Generated by Django 3.1.7 on 2021-07-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0017_auto_20210702_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(max_length=1000)),
                ('citationMLA', models.TextField(blank=True, default='', max_length=2000)),
                ('citationAPA', models.TextField(blank=True, default='', max_length=2000)),
                ('citationChicago', models.TextField(blank=True, default='', max_length=2000)),
                ('paper', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='skepsi_app.paper')),
            ],
        ),
    ]
