# Generated by Django 3.1.7 on 2021-07-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0018_auto_20210702_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='paperOrder',
            field=models.IntegerField(default=1),
        ),
    ]
