# Generated by Django 3.1.7 on 2021-07-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0019_reference_paperorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='title',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
