# Generated by Django 3.1.7 on 2021-07-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0020_reference_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='citationAPA',
            new_name='citation',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='citationChicago',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='citationMLA',
        ),
    ]
