# Generated by Django 3.1.7 on 2021-07-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0023_auto_20210703_0011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('paper', 'paperOrder')},
        ),
    ]
