# Generated by Django 3.1.7 on 2021-07-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0024_auto_20210703_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
