# Generated by Django 3.1.7 on 2021-07-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0025_paper_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='created_date',
            field=models.CharField(default='', max_length=500),
        ),
    ]
