# Generated by Django 3.1.7 on 2021-07-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0026_paper_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('Validity', 'Validity'), ('Novelty', 'Novelty'), ('Domain Importance', 'Domain Importance')], default='Validity', max_length=100)),
                ('explanation', models.TextField(max_length=10000)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='skepsi_app.annotation')),
            ],
        ),
    ]
