# Generated by Django 3.1.7 on 2021-07-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0027_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='paper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='skepsi_app.paper'),
        ),
    ]
