# Generated by Django 3.1.7 on 2021-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0028_auto_20210708_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(blank=True, choices=[('Validity', 'Validity'), ('Novelty', 'Novelty'), ('Domain Importance', 'Domain Importance')], default='Validity', max_length=100, null=True),
        ),
    ]
