# Generated by Django 3.1.7 on 2021-07-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0029_auto_20210708_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='skepsi_app.paper')),
            ],
        ),
    ]
