# Generated by Django 3.1.7 on 2021-07-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0030_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='figure_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='figure',
            name='name',
            field=models.TextField(default='', max_length=2500),
        ),
    ]
