# Generated by Django 3.1.7 on 2021-07-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0032_auto_20210715_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='caption',
            field=models.TextField(default='', max_length=50000),
        ),
    ]
