# Generated by Django 3.1.7 on 2021-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0033_figure_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='field',
            field=models.CharField(blank=True, choices=[('Validity', 'Validity'), ('Novelty', 'Novelty'), ('Domain Importance', 'Domain Importance')], default='Validity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 10)), name='A score is valid between 1 and 10 (inclusive)'),
        ),
    ]
