# Generated by Django 3.1.7 on 2021-07-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0038_auto_20210715_1910'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='score',
            name='A score is valid between 1 and 10 (inclusive)',
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 10)), name='A score is valid between 1 and 10 (inclusive)'),
        ),
    ]
