# Generated by Django 3.1.7 on 2021-07-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0039_auto_20210715_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
