# Generated by Django 3.1.7 on 2021-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0040_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
