# Generated by Django 3.1.7 on 2021-07-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skepsi_app', '0041_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='md',
            field=models.TextField(default='', max_length=500000),
        ),
    ]
